### ISSUE TITLE
'Fork me on Github' link is not clickable when navbar is collapsed for smaller screens 

### ISSUE THREAD

**Issue by dropofwill** [ryansb/ofCourse#20]
The list items from the nabber cover the 'Fork me on Github' link when it is collapsed for smaller screens. making it impossible to click:

![screen shot 2015-02-06 at 1 33 46 pm](https://cloud.githubusercontent.com/assets/3129448/6085105/d2640a58-ae04-11e4-8c25-454a31da7302.png)

It's an easy enough fix with a couple lines of css (adjust the width of the li's or the z-index/positioning =), but I'm not super familiar with Bootstrap, so there might be a way to fix this with its built in classes.

Confirmed on Safari 8 in OS X and Chromium 40 in Arch.

**Comment by ryansb** [comment]
Would it be better to just get rid of "fork me on github" on smaller screens? I feel like tablet users probably don't do a lot of dev work on those devices.

**Comment by dropofwill** [comment]
Yeah, but it enters that mode pretty early at <1200px, which is pretty close to how I browse on my laptop (1/3 terminal, 2/3 browser), so this covers more than just touch devices.

Either way it's not a big deal, because it's pretty straightforward to find the repo. Hiding it on small screens would be better than leaving it broken.
