### ISSUE TITLE
Stess test service on openshift

### ISSUE THREAD

**Issue by ryansb** [ryansb/ofCourse#25]
See how well flask can handle huge (150+) classes.

**Comment by liam-middlebrook** [comment]
We can stress test with the generated YAML files from here ( https://github.com/liam-middlebrook/rant-people/releases/tag/0.0.0 )

**Comment by liam-middlebrook** [comment]
Currently stress testing on http://github.com/liam-middlebrook/ofcourse-content-test.git

**Comment by ryansb** [comment]
Did you do any measurement of latency/perf on this, or just check if it loaded or not?

**Comment by ryansb** [comment]
@liam-middlebrook Did anything come of this testing?
