### ISSUE TITLE
Firstflight needs avatar instructions

### ISSUE THREAD

**Issue by mellolikejello** [ryansb/ofCourse#30]
@decause says this section needs a "how-to" for uploading and using libra/gravatar

**Comment by ryansb** [comment]
Firstflight is a part of the course, not the courseware. Shouldn't the libravatar docs be there instead?

**Comment by liam-middlebrook** [comment]
@ryansb firstflight is shipped default with ofCourse. It does make sense to add these instructions to the templates since that's how the Participants Page and Participant's Pages pull student avatar data.

**Comment by ryansb** [comment]
Oh. My bad, forgot we shipped w/ some curriculum.
