### ISSUE TITLE
Missing profile.mak?

### ISSUE THREAD

**Issue by mellolikejello** [ryansb/ofCourse#31]
@liam-middlebrook 
http://hfoss-ritigm.rhcloud.com/participants/2015/spring/mellolikejello

when I click on someone's name on the participants page, I get a 500 error

**Comment by ryansb** [comment]
Your yaml file doesn't have a `name` field.

You must have a name field. It doesn't have to be your real name, but it does have to be *a* name.

**Comment by ryansb** [comment]
Also you can (and should) run ofcourse locally to test your YAML before submitting it, or to check out errors you find.

**Comment by mellolikejello** [comment]
:+1: thanks!
