### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by ryansb** [ryansb/ofCourse#37]
Prior to the ofCourse migration @kocsenc pointed out that we lack a favicon (which is still the case).

_ported from decause/hflossk#433_

**Comment by ritjoe** [comment]
WilfriedE has got some icons for FOSS@RIT

https://github.com/wilfriedE/hfoss/commit/34f7825e8f18343bf729a0f4a8bdcac561813435

which are now deployed.

In principle, those are still site-specific, so maybe the idea is that someone would make one for ofCourse itself as a good default to use?

**Comment by ryansb** [comment]
I don't mind having them as the default, since ofCourse is still a <strike>fossbox</strike> FOSS@MAGIC project. I'll ask him if that's kosher.
