### ISSUE TITLE
Blog Post Count Labels Are Indistinguishable in Color

### ISSUE THREAD

**Issue by liam-middlebrook** [ryansb/ofCourse#43]
I can't tell the different between the colors for the different blog post counts anymore. Here's an example that [shows this issue](http://bizlegfoss-ritigm.rhcloud.com/participants/)

**Comment by ryansb** [comment]
Hm. Looks like in the Great Re-Theming they all got classed `label-danger`. @mellolikejello can you take a look at this?

**Comment by liam-middlebrook** [comment]
They aren't all label danger. Mine is the only one  at the count and should be at success. I'm just not sure the colors are different.

**Comment by msoucy** [comment]
Agreed, "danger" and "close-to-success" are way too similar...

**Comment by ryansb** [comment]
@msoucy by "close-to-success" do you mean `label-warning`?

**Comment by ryansb** [comment]
How does this strike you
![sample](https://cloud.githubusercontent.com/assets/636610/6922098/cf48dc16-d796-11e4-9d2d-8f9041292c0c.png)

**Comment by msoucy** [comment]
Yeah, `label-warning` is the name. I couldn't see an example on the page at the time.
