### ISSUE TITLE
Better scheduling

### ISSUE THREAD

**Issue by msoucy** [ryansb/ofCourse#55]
Instead of editing the template's HTML, it should be possible to edit a YAML or similar instead - some form of simple list of class dates/topics/due/assigned, plus a hackathon/event list, that get automatically sorted by date and displayed.

@ritjoe and I have been discussing this a bit

**Comment by ryansb** [comment]
What do you think would be a sensible format? I'd like to avoid inventing our own format entirely, maybe we could leverage iCal or another existing format?

**Comment by msoucy** [comment]
[vobject](https://pypi.python.org/pypi/vobject) looks like it supports iCalendar and vCard, which are (from the looks of it) very similar. There's also something called hCalendar that looks marginally nicer (human-"readable" XML), but I'm not sure if it's worth using since it's seemingly less common...

**Comment by msoucy** [comment]
Closed per #58 and #60
