### ISSUE TITLE
example workflow diagram

### ISSUE THREAD

**Issue by ritjoe** [ryansb/ofCourse#63]
In talking with SJ last week about setting up and running a course with ofCourse we struck on the idea of some sort of diagram showing the relation of the various pieces.  

Such a diagram might also be useful to the students in such a course.

I've got a diagram in the works the labels for which I'm not entirely comfortable, but I'll try to get it in as a PR for the Hive Mind to accept, reject, or improve.

**Comment by ryansb** [comment]
Going to close this issue in lieu of PR #65 since that'll cover this.
