### ISSUE TITLE
Link (non hovering, non clicked) color is indifferent from base text  color

### ISSUE THREAD

**Issue by spg1502** [ryansb/ofCourse#66]
It looks like material-wfont.min.css (and a handful of other css stuff) are overloading the color for links in blocks of text. This is making all link text look indistinguishable from non-link text making it difficult to identify which lines of text on the page are links.

Might be worth fixing so that links are more easily identifyable!

**Comment by liam-middlebrook** [comment]
Can you give a screenshot or list an example of this?

**Comment by spg1502** [comment]
Here's an example. In the first image I'm unable to tell what text in the green div is a link, and in the second I hover over it so it's highlighted. This specific content appears on this page: http://hfoss-ritjoe.rhcloud.com/hw/firstflight

![freshlink](https://cloud.githubusercontent.com/assets/9612032/12620363/10c49928-c4ea-11e5-9a37-3b1d05b5fc41.png)

![hoverlink](https://cloud.githubusercontent.com/assets/9612032/12620364/10c80cfc-c4ea-11e5-9e33-c022dad30084.png)

Inspecting the link itself indicates that it inherited the #FFFFFF color for links from material-wfont.min.css

**Comment by spg1502** [comment]
Looking to fix this as a part of the FOSS course's bugfix assignment, but before I go messing with material-wfont.min.css I was hoping to get some context about why the color for links was overloaded in that file. It looks like @mellolikejello was the contributor that added that file in this commit ( https://github.com/ryansb/ofCourse/commit/bee11223b44deedfb3e53b96fffb5133e38aa6f9 ).

Any chance you could give me some context to why white was chosen as the color to overload link colors? If it was a conscious decision and there's a reason, I'll happily move on and find another bug, but I'd love to squash my own bug that I identified for the course if appropriate!

**Comment by mellolikejello** [comment]
@spg1502 material-wfont.min.css (+ material.min.css and ripples.min.css) come directly from http://fezvrasta.github.io/bootstrap-material-design/

These CSS files were used to migrate ofcourse to material design, so this link color was part of the mass update (and not exactly a deliberate selection). There are definitely places where the CSS can be polished for ofcourse usage. Tweaking should be done in site.css (not in *.min.css files). 

Thanks for checking!

**Comment by spg1502** [comment]
Thanks for the reply! I think I'll take care of this as a part of the bugfix assignment for the FOSS class. Should I assign this bug to myself?

**Comment by ryansb** [comment]
Yup, go right ahead

**Comment by spg1502** [comment]
Doesn't look like I have the proper access to this repo to assign it to myself unfortunately (usually if you have the proper access, there's a checkbox next to the issue in the issue browser you can select, then pick an assignee for it and I don't have that checkbox) so if someone with the proper access wouldn't mind taking care of assigning this to me I would appreciate it!

Additionally, I'm looking into setting up a local environment in which I can test my changes, from what I've gathered from the readthedocs I need virtualenv installed locally, but of the two versions available on the linked site [here](https://pypi.python.org/pypi/virtualenv#downloads) which should I be using?

**Comment by ryansb** [comment]
Those are two different distribution types, ping me in #rit-foss and I'll help you get set up.

**Comment by msoucy** [comment]
@spg1502 that only appears when you are specifically marked as a contributor for the repository, and is used to track which of the project maintainers are working on it. In your situation (as a pull request), it's normally sufficient to just comment on the issue saying that you're working on it, if you want to avoid  others working on the same problem.

**Comment by spg1502** [comment]
@mellolikejello I ran into a small issue with the method you suggested. As seen in the screenshots I posted earlier, the style from material-wfont.min.css is taking priority over the site.css attribute for link color. Any changes I make to the link font color in site.css get overwritten by material-wfont.min.css

In the header for the page, site.css is the last stylesheet that gets set, so I would imagine that would be the stylesheet that would take priority (and override any css set in the other style sheets) however this does not appear to be the case.

Would anyone happen to know why the link color modifier in material-wfont.min.css is taking priority over the link color modifier in site.css even though material-wfont.min.css is listed BEFORE site.css in the header?

**Comment by ryansb** [comment]
It's specificity over heirarchy. The w-font.min.css file has a higher specificity on the font color.

Specifically, the rule in site.css is on the specifier `a, .alert code>a` and the one in w-font.min.css specifies `.alert a, .alert .alert-link`.

If you make the site.css specifier equally specific by adding `.alert a` then its color will win.

**Comment by spg1502** [comment]
AH! Thanks for clearing that up, I wasn't aware that there were other factors besides load order that gave CSS rules precedence.

**Comment by ryansb** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity
