### ISSUE TITLE
course but not ofcourse deployed to openshift

### ISSUE THREAD

**Issue by ritjoe** [ryansb/ofCourse#73]
"ofcourse openshift --app foo --domain bar" seems to complete successfully, but hitting the URL yields an internal server error.

this app-root/logs/python.log from my test instance:

<pre>
[Tue Mar 29 13:54:26 2016] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:openshift_t:s0:c6,c834
[Tue Mar 29 13:54:26 2016] [notice] Digest: generating secret for digest authentication ...
[Tue Mar 29 13:54:26 2016] [notice] Digest: done
[Tue Mar 29 13:54:26 2016] [notice] Apache/2.2.15 (Unix) mod_wsgi/3.4 Python/2.7.8 configured -- resuming normal operations
[Tue Mar 29 13:58:23 2016] [notice] caught SIGWINCH, shutting down gracefully
- - - [29/Mar/2016:13:58:23 -0400] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.2.15 (Red Hat) (internal dummy connection)"
[Tue Mar 29 13:58:30 2016] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:openshift_t:s0:c6,c834
[Tue Mar 29 13:58:30 2016] [notice] Digest: generating secret for digest authentication ...
[Tue Mar 29 13:58:30 2016] [notice] Digest: done
[Tue Mar 29 13:58:30 2016] [notice] Apache/2.2.15 (Unix) mod_wsgi/3.4 Python/2.7.8 configured -- resuming normal operations
[Tue Mar 29 13:58:52 2016] [error] [client 127.13.147.129] mod_wsgi (pid=200304): Target WSGI script '/var/lib/openshift/56fac0b92d52718bc70000d9/app-root/runtime/repo/wsgi.py' cannot be loaded as Python module.
[Tue Mar 29 13:58:52 2016] [error] [client 127.13.147.129] mod_wsgi (pid=200304): Exception occurred processing WSGI script '/var/lib/openshift/56fac0b92d52718bc70000d9/app-root/runtime/repo/wsgi.py'.
[Tue Mar 29 13:58:52 2016] [error] [client 127.13.147.129] Traceback (most recent call last):
[Tue Mar 29 13:58:52 2016] [error] [client 127.13.147.129]   File "/var/lib/openshift/56fac0b92d52718bc70000d9/app-root/runtime/repo/wsgi.py", line 14, in <module>
[Tue Mar 29 13:58:52 2016] [error] [client 127.13.147.129]     import ofcourse.site
[Tue Mar 29 13:58:52 2016] [error] [client 127.13.147.129] ImportError: No module named ofcourse.site
104.153.29.246 - - [29/Mar/2016:13:58:52 -0400] "GET / HTTP/1.1" 500 631 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:44.0) Gecko/20100101 Firefox/44.0"
</pre>

When I search through the root directory of the openshift gear, it looks like the course directory deployed, but that none of the virtual environment deployed (eg, I find no ofcourse-specific files, consistent with the ImportError above).

**Comment by ryansb** [comment]
This is due to the openshift pypi mirrors not having ofcourse 0.2.4 yet, they should pick it up soon.
