### ISSUE TITLE
Version skew with pypi, where did this print statement come from?

### ISSUE THREAD

**Issue by ritjoe** [ryansb/ofCourse#76]
OK, I'm giving this another go. 

The version of openshift_utils.py installed during a pip install seems to be the same as found in the latest version here:

https://pypi.python.org/packages/1c/02/ebbcfce84eb89151390c4c2a3272c525671df0a4dcd070450a5d0b2bf535/ofcourse-0.2.4.tar.gz

on pypi:

https://pypi.python.org/pypi/ofcourse

But it generates this error:

```
Traceback (most recent call last):
  File "/home/joe/scripted-ofcourse/testofcourse-F16/ofcourse_environment/bin/ofcourse", line 7, in <module>
    from ofcourse.cli import cli
  File "/home/joe/scripted-ofcourse/testofcourse-F16/ofcourse_environment/lib/python3.5/site-packages/ofcourse/cli/__init__.py", line 14, in <module>
    from ofcourse.cli.openshift_utils import (generate_token,
  File "/home/joe/scripted-ofcourse/testofcourse-F16/ofcourse_environment/lib/python3.5/site-packages/ofcourse/cli/openshift_utils.py", line 85
    print os.getcwd()
           ^
SyntaxError: invalid syntax
```
However, the version in current HEAD does not have the offending print statement:

https://github.com/ryansb/ofCourse/blob/develop/ofcourse/cli/openshift_utils.py

for either branch develop as above or branch master:

https://github.com/ryansb/ofCourse/blob/master/ofcourse/cli/openshift_utils.py

even though the latest tagged release is 0.2.4 

I've just started digging through commit hisory to try to find out when the print statement was there, and when it was removed. Also, I don't know much about how code gets from github into pypi, but there seems to be a problem with that. Do we need the current version tagged so that it will be pulled into pypi or what?

Please advise.

**Comment by ritjoe** [comment]
I'm hoping this has relevance for #70 #74 and #75

This is with python3 (3.5.1) in Fedora24 Workstation x86_64. I'm trying it in a fairly clean KVM instance using a variant of the script from #75

https://github.com/ryansb/ofCourse/files/201486/script.txt

in which I've added lines to make sure the user.name and user.email are set.

**Comment by ryansb** [comment]
It was because I uploaded to pypi from a dirty working directory - my fault. I've made a new .2.5 tag and published that, without the offending `print`.
